name: Dakara_rand

on:
  schedule:
    - cron: '11 18,19,21,22 * * *'

  workflow_dispatch:

jobs:

  daka_rand:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Random
        id: continueToRun
        run: python ./src/rand.py
        continue-on-error: true

      - name: Install Selenium
        if:  ${{ contains(steps.continueToRun.outcome, 'success') }}
        run: pip install selenium
      
      - name: Random Delay
        if:  ${{ contains(steps.continueToRun.outcome, 'success') }}
        env: 
          MY_SECRET_USERNAME: ${{ secrets.MY_SECRET_USERNAME }}
          MY_SECRET_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
          MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
          MY_SECRET_LOCATION: ${{ secrets.MY_SECRET_LOCATION }}
        run: python ./src/delay.py

      - name: Payload
        if:  ${{ contains(steps.continueToRun.outcome, 'success') }}
        env: 
          MY_SECRET_USERNAME: ${{ secrets.MY_SECRET_USERNAME }}
          MY_SECRET_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
          MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
          MY_SECRET_LOCATION: ${{ secrets.MY_SECRET_LOCATION }}
        run: python ./src/daka.py
        